### ISSUE TITLE
Why I can't compile the project.

### ISSUE THREAD

**Issue by hawaiiandycao** [mapgears/ol3-panzoom#4]
Why I can't compile the project ?

E:\ol3-panzoom-0.1>node build/build.js build/ol3pz.json build/ol3pz.js
info ol3-panzoom Parsing dependencies
info ol3-panzoom Compiling 29 sources
ERR! compile java.lang.NullPointerException: No warning class for name: checkProvides
ERR! compile

**Comment by adube** [comment]
What node version are you using ?  Also, you should do the following steps to build:

```
npm install
make dist
```

**Comment by adube** [comment]
I just tested with node 4.2 on my Linux machine and the above commands worked fine.  Would you please test again ?

**Comment by Renaud009** [comment]
I just tried with node 4.2
$ nvm use 4.2
$ npm install
$ make dist
find: ‘examples/data/’: Aucun fichier ou dossier de ce type
(cd ol3 && npm install && node tasks/generate-externs.js build/ol-externs.js)
module.js:328
    throw err;
    ^

Error: Cannot find module '/DIR/ol3/tasks/generate-externs.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
make: *** [ol3/build/ol-externs.js] Erreur 1

**Comment by adube** [comment]
@Renaud009 I just pushed something.  Would you please update your local repository and try again to see if it fixes the issue?

**Comment by Renaud009** [comment]
Same error here after pulling with node 4.2.6 on centos7.1 x86_64
